### ISSUE TITLE
[meta] Sync prototyping

### ISSUE THREAD

**Issue by rnewman** [mozilla/mentat#495]
We've identified a number of small changes and additions to Mentat in order for it to support sync prototyping. These are:

- [ ] Switching txes to use a **transaction UUID** for identification rather than an entid in a specified part. UUIDs are stable and globally unique, which makes them suitable for identifying non-smushable entities. This also opens the part space to be entirely free for user entities. A transaction identifier can now be a distinct type alongside `ref` and `uuid`. Naturally some work is needed to allow transactions in the `e` position. This is a departure from Datomic compatibility. We'll need a transaction sequence number, too, to provide ordering of transactions.
- [ ] Implementing **renumbering** of entities and transaction sequence numbers: the shifting of allocated identifiers to avoid inadvertent collision with identifiers allocated on other devices, and the repositioning of transacted data to implement rebasing.
- [ ] Exposing an operation for **raw assertion**: asserting datoms with a defined `tx` and sequence. This is how we'll copy remote transactions into the local store.
- [ ] Implementing deliberate **collision**. Given an identifying attribute `:foo/id`, a local (renumbered) datom `[1234 :foo/id "bar"]`, and a remote datom `[1212 :foo/id "bar"]`, we want to replace `1234` with `1212` throughout a specified range of transactions. `1234` and `1212` will typically have been allocated since the last sync. This is just like upserting except we want to take the remote entid, and we'll have less work to do because we already have a fully formed graph.

With these primitives we'll be able to prototype some kinds of syncing: straightforward replication, rebases, and lossy merges.

**Comment by rfk** [comment]
>  We'll need a transaction sequence number, too, to provide ordering of transactions

A local sequence number for use by the client, or global?

**Comment by rnewman** [comment]
> A local sequence number for use by the client, or global?

The client. My expectation is that we will serialize transactions into explicitly sequential formats for the wire and the server — sequences of changesets containing sequences of transactions — and the server can then maintain sequentiality however makes sense for it.

Mentat stores data locally in relational tables, which are not intrinsically ordered, so we need to add something for us to `ORDER BY` and filter on.

**Comment by ncalexan** [comment]
> We've identified a number of small changes and additions to Mentat in order for it to support sync prototyping. These are:
> 
>     Switching txes to use a transaction UUID for identification rather than an entid in a specified part. UUIDs are stable and globally unique, which makes them suitable for identifying non-smushable entities. This also opens the part space to be entirely free for user entities. A transaction identifier can now be a distinct type alongside ref and uuid. Naturally some work is needed to allow transactions in the e position. This is a departure from Datomic compatibility. We'll need a transaction sequence number, too, to provide ordering of transactions.

Urgh.  This really changes a lot of the assumptions that Datomic makes.  Could we parameterize the existing expression over the tx space, allowing both sequential integers and GUIDs?  (I assume you're not differentiating between Universal UID and Global UID.)

>     Implementing renumbering of entities and transaction sequence numbers: the shifting of allocated identifiers to avoid inadvertent collision with identifiers allocated on other devices, and the repositioning of transacted data to implement rebasing.

This is a reasonable internal primitive to implement independent of any other changes.  It's what one would need to do to allow resizing `:db/part` declarations, for example.  Full steam ahead on this one!

>     Exposing an operation for raw assertion: asserting datoms with a defined tx and sequence. This is how we'll copy remote transactions into the local store.

Ditto with this.  It's how one might clone `:db/part` contents across very similar stores.

>     Implementing deliberate collision. Given an identifying attribute :foo/id, a local (renumbered) datom [1234 :foo/id "bar"], and a remote datom [1212 :foo/id "bar"], we want to replace 1234 with 1212 throughout a specified range of transactions. 1234 and 1212 will typically have been allocated since the last sync. This is just like upserting except we want to take the remote entid, and we'll have less work to do because we already have a fully formed graph.

Can you elaborate on this?  I don't see your use case, so I'm having trouble understanding what you'll need to change in the existing upsert mechanism.

**Comment by rnewman** [comment]
> Urgh. This really changes a lot of the assumptions that Datomic makes.

I don't think it changes that many.

Datomic as a single-source-of-truth system expects that tx IDs are stable; tx UUIDs will be stable. It expects that transactions are sequential; tx sequence numbers will be sequential.

Three assumptions will change, I think:

- Datomic users typically assume that txInstants increase alongside tx numbers. That's a broken assumption anyway thanks to clocks.
- In the presence of sync it's possible for the transaction sequence to be non-linear (branching and merging), and/or for the transaction sequence itself to change (rebasing).
- In Datomic the space of transactions is a subset of the space of entities; the same attributes can relate tx-entities and entity-entities (that is: they're both `db.type/ref`). I think it's _valuable_ to split these two.

Are there any assumptions that I'm missing?

**Comment by rnewman** [comment]
> Can you elaborate on this? I don't see your use case, so I'm having trouble understanding what you'll need to change in the existing upsert mechanism.

We discussed this a little on Slack.

In short: we need some mechanism for declaring that two entity IDs — in our case, one entity ID that was assigned remotely since the last sync, and one that was assigned locally since the last sync — are the same.

This is a primitive that a space of possible smushing algorithms can use to make the store reflect their deduction.

The existing tempid mechanism is one such approach:

- Remove the local datoms from `datoms` and `tx`. ("Rollback")
- Insert the remote datoms.
- Reword them to use tempids instead of the candidate set of IDs.
- Re-transact, using upserts to smush the old local data against the new remote data.

But that's pretty heavyweight, and we can probably get some or all of the way there by determining equivalences and then rewriting numbers.
