### ISSUE TITLE
[meta] Interop and local flag days

### ISSUE THREAD

**Issue by rnewman** [mozilla/mentat#587]
There are a number of changes to Mentat's storage schema and capabilities that are an 'event horizon' for syncing: older clients would be unable to sync across it.

We will be addressing this via [built-in schema versioning](https://github.com/mozilla/mentat/blob/66e6fef75ea65abd5e4c178f07022334324cebbe/src/vocabulary.rs#L389), but it's prudent to track work that would trigger this.

- [ ] More datatypes (#201): big integers (#280), JSON (#31), non-ns keywords (#285), URIs (#431)
- [ ] Directory-based and alternate file format (#97, #129, #541)
- [ ] Alternate datom flag format (#29) 
- [ ] More schema alteration support and simpler transacts for schema changes (#105, #379, #121)
- [ ] Excision (#21)
- [ ] `:db/noHistory` (#102)
- [ ] Hash-based indexing (#69)
- [ ] Tabular representations (#33)
